import { NextResponse } from 'next/server';
import pptxgen from 'pptxgenjs';

interface Slide {
    title: string;
    content: string[];
    imageKeyword: string;
}

interface PresentationData {
    title: string;
    slides: Slide[];
}

export async function POST(req: Request) {
    try {
        const body: PresentationData = await req.json();
        const { title, slides } = body;

        if (!title || !slides || slides.length === 0) {
            return NextResponse.json(
                { error: 'Invalid presentation data' },
                { status: 400 }
            );
        }

        const pptx = new pptxgen();

        // Set Metadata
        pptx.author = "BusinessAI";
        pptx.company = "BusinessAI SaaS";
        pptx.title = title;

        // Create Slides
        for (const slideData of slides) {
            const slide = pptx.addSlide();

            // Background color
            slide.background = { color: "FFFFFF" };

            // Title
            slide.addText(slideData.title, {
                x: 0.5,
                y: 0.5,
                w: "90%",
                h: 1,
                fontSize: 32,
                bold: true,
                color: "363636",
            });

            // Content Bullets
            if (slideData.content && slideData.content.length > 0) {
                const bullets = slideData.content.map(text => ({
                    text,
                    options: { fontSize: 18, color: "595959", breakLine: true }
                }));

                slide.addText(bullets as any, {
                    x: 0.5,
                    y: 1.8,
                    w: "50%",
                    h: 4,
                    bullet: true,
                });
            }

            // Image from Pollinations AI
            if (slideData.imageKeyword) {
                const imageUrl = `https://image.pollinations.ai/prompt/${encodeURIComponent(slideData.imageKeyword)}?width=1024&height=1024&nologo=true`;

                try {
                    slide.addImage({
                        path: imageUrl,
                        x: 5.5,
                        y: 1.8,
                        w: 4,
                        h: 3,
                    });
                } catch (e) {
                    console.error("Failed to add image to slide", e);
                }
            }

            // Footer
            slide.addText("Generated by BusinessAI", {
                x: 0.5,
                y: 5.2,
                fontSize: 10,
                color: "AAAAAA"
            });
        }

        // Generate the PPTX as a base64 string
        const pptxBase64 = await pptx.write({ outputType: 'base64' }) as string;

        // Convert base64 to buffer
        const buffer = Buffer.from(pptxBase64, 'base64');

        // Return as downloadable file
        return new NextResponse(buffer, {
            status: 200,
            headers: {
                'Content-Type': 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
                'Content-Disposition': `attachment; filename="${title.replace(/[^a-z0-9]/gi, '_')}.pptx"`,
            },
        });

    } catch (error: any) {
        console.error('Error generating PPTX:', error);
        return NextResponse.json(
            { error: error.message || 'Failed to generate presentation file' },
            { status: 500 }
        );
    }
}
