import { NextResponse } from 'next/server';
import pptxgen from 'pptxgenjs';

interface Slide {
    title: string;
    content: string[];
    imageKeyword: string;
}

interface Theme {
    id: string;
    name: string;
    colors: {
        primary: string;
        secondary: string;
        accent: string;
    };
}

interface PresentationData {
    title: string;
    slides: Slide[];
    theme?: Theme;
}

export async function POST(req: Request) {
    try {
        const body: PresentationData = await req.json();
        const { title, slides, theme } = body;

        if (!title || !slides || slides.length === 0) {
            return NextResponse.json(
                { error: 'Invalid presentation data' },
                { status: 400 }
            );
        }

        const pptx = new pptxgen();

        // Set Metadata
        pptx.author = "BusinessAI";
        pptx.company = "BusinessAI SaaS";
        pptx.title = title;
        pptx.subject = "AI Generated Presentation";

        // Theme colors
        const primaryColor = theme?.colors?.primary?.replace('#', '') || '1e40af';
        const secondaryColor = theme?.colors?.secondary?.replace('#', '') || '3b82f6';
        const accentColor = theme?.colors?.accent?.replace('#', '') || '60a5fa';

        // Create Slides
        for (let i = 0; i < slides.length; i++) {
            const slideData = slides[i];
            const slide = pptx.addSlide();
            const isFirstSlide = i === 0;
            const isLastSlide = i === slides.length - 1;

            if (isFirstSlide) {
                // TITLE SLIDE - Full gradient background with centered content
                slide.background = {
                    color: primaryColor,
                };

                // Add gradient overlay shape
                slide.addShape('rect', {
                    x: 0,
                    y: 0,
                    w: '100%',
                    h: '100%',
                    fill: {
                        type: 'solid',
                        color: primaryColor
                    },
                });

                // Decorative accent shape
                slide.addShape('rect', {
                    x: 0,
                    y: 4.5,
                    w: '100%',
                    h: 0.1,
                    fill: { color: accentColor },
                });

                // Title
                slide.addText(slideData.title, {
                    x: 0.5,
                    y: 1.5,
                    w: 5.5,
                    h: 2,
                    fontSize: 44,
                    bold: true,
                    color: 'FFFFFF',
                    fontFace: 'Arial',
                    align: 'left',
                    valign: 'middle',
                });

                // Subtitle from content
                if (slideData.content && slideData.content.length > 0) {
                    slide.addText(slideData.content.join(' '), {
                        x: 0.5,
                        y: 3.5,
                        w: 5.5,
                        h: 1,
                        fontSize: 18,
                        color: 'FFFFFF',
                        fontFace: 'Arial',
                        align: 'left',
                        valign: 'top',
                    });
                }

                // Image on right side
                if (slideData.imageKeyword) {
                    const imageUrl = `https://image.pollinations.ai/prompt/${encodeURIComponent(slideData.imageKeyword)}?width=800&height=600&nologo=true`;
                    try {
                        slide.addImage({
                            path: imageUrl,
                            x: 6.2,
                            y: 0.8,
                            w: 3.3,
                            h: 4,
                            rounding: true,
                        });
                    } catch (e) {
                        console.error("Failed to add title image", e);
                    }
                }

                // Footer
                slide.addText("Generated by BusinessAI", {
                    x: 0.5,
                    y: 5.1,
                    w: 4,
                    fontSize: 10,
                    color: 'FFFFFF',
                    fontFace: 'Arial',
                });

            } else if (isLastSlide) {
                // THANK YOU SLIDE - Centered content
                slide.background = { color: primaryColor };

                slide.addText(slideData.title, {
                    x: 0,
                    y: 2,
                    w: '100%',
                    h: 1.5,
                    fontSize: 48,
                    bold: true,
                    color: 'FFFFFF',
                    fontFace: 'Arial',
                    align: 'center',
                    valign: 'middle',
                });

                if (slideData.content && slideData.content.length > 0) {
                    slide.addText(slideData.content.join('\n'), {
                        x: 1,
                        y: 3.5,
                        w: 8,
                        h: 1.5,
                        fontSize: 18,
                        color: 'FFFFFF',
                        fontFace: 'Arial',
                        align: 'center',
                        valign: 'top',
                    });
                }

            } else {
                // CONTENT SLIDES - Professional two-column layout
                slide.background = { color: 'FFFFFF' };

                // Top accent bar
                slide.addShape('rect', {
                    x: 0,
                    y: 0,
                    w: '100%',
                    h: 0.08,
                    fill: { color: primaryColor },
                });

                // Slide number badge
                slide.addShape('rect', {
                    x: 0,
                    y: 0.3,
                    w: 0.5,
                    h: 0.5,
                    fill: { color: secondaryColor },
                });
                slide.addText(String(i + 1), {
                    x: 0,
                    y: 0.3,
                    w: 0.5,
                    h: 0.5,
                    fontSize: 14,
                    bold: true,
                    color: 'FFFFFF',
                    fontFace: 'Arial',
                    align: 'center',
                    valign: 'middle',
                });

                // Title
                slide.addText(slideData.title, {
                    x: 0.7,
                    y: 0.3,
                    w: 9,
                    h: 0.7,
                    fontSize: 28,
                    bold: true,
                    color: '1f2937',
                    fontFace: 'Arial',
                });

                // Content bullets on left
                if (slideData.content && slideData.content.length > 0) {
                    const bullets = slideData.content.map((text) => ({
                        text,
                        options: {
                            fontSize: 16,
                            color: '4b5563',
                            bullet: { type: 'bullet', color: secondaryColor },
                            breakLine: true,
                            paraSpaceAfter: 12,
                        },
                    }));

                    slide.addText(bullets as any, {
                        x: 0.5,
                        y: 1.3,
                        w: 5,
                        h: 3.5,
                        fontFace: 'Arial',
                        valign: 'top',
                    });
                }

                // Image on right
                if (slideData.imageKeyword) {
                    const imageUrl = `https://image.pollinations.ai/prompt/${encodeURIComponent(slideData.imageKeyword)}?width=800&height=600&nologo=true`;
                    try {
                        slide.addImage({
                            path: imageUrl,
                            x: 5.8,
                            y: 1.3,
                            w: 3.8,
                            h: 3.2,
                            rounding: true,
                        });
                    } catch (e) {
                        console.error("Failed to add slide image", e);
                    }
                }

                // Footer
                slide.addText(`${title}`, {
                    x: 0.5,
                    y: 5,
                    w: 5,
                    fontSize: 9,
                    color: '9ca3af',
                    fontFace: 'Arial',
                });

                slide.addText(`${i + 1} / ${slides.length}`, {
                    x: 8.5,
                    y: 5,
                    w: 1,
                    fontSize: 9,
                    color: '9ca3af',
                    fontFace: 'Arial',
                    align: 'right',
                });
            }
        }

        // Generate the PPTX as a base64 string
        const pptxBase64 = await pptx.write({ outputType: 'base64' }) as string;

        // Convert base64 to buffer
        const buffer = Buffer.from(pptxBase64, 'base64');

        // Return as downloadable file
        return new NextResponse(buffer, {
            status: 200,
            headers: {
                'Content-Type': 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
                'Content-Disposition': `attachment; filename="${title.replace(/[^a-z0-9]/gi, '_')}.pptx"`,
            },
        });

    } catch (error: any) {
        console.error('Error generating PPTX:', error);
        return NextResponse.json(
            { error: error.message || 'Failed to generate presentation file' },
            { status: 500 }
        );
    }
}
