"use client";
import React, { useEffect, useRef } from "react";
import { SandpackPreview, useSandpack, SandpackPreviewRef } from "@codesandbox/sandpack-react";
import { useContext } from "react";
import { ActionContext } from "@/contexts/ActionContext";
import JSZip from "jszip";
import { saveAs } from "file-saver";

function SandpackPreviewClient() {
    const previewRef = useRef<SandpackPreviewRef>(null);
    const { sandpack } = useSandpack();
    const { action, setAction } = useContext(ActionContext);

    useEffect(() => {
        GetSandpackClient();
    }, [action]);

    const downloadAsZip = async () => {
        try {
            const zip = new JSZip();
            const { files } = sandpack;

            // Add all files to the zip with proper folder structure
            Object.entries(files).forEach(([filename, fileContent]) => {
                const cleanFilename = filename.startsWith("/")
                    ? filename.substring(1)
                    : filename;

                const content =
                    typeof fileContent === "string" ? fileContent : fileContent.code;

                zip.file(cleanFilename, content);
            });

            // Add README with setup instructions
            const readme = `# AI-Generated Landing Page

This is a production-ready React application generated by AI.

## 🚀 Quick Start

### Prerequisites
- Node.js 14+ installed
- npm or yarn package manager

### Installation

1. Extract this ZIP file
2. Open terminal in the project folder
3. Install dependencies:
   \`\`\`bash
   npm install
   \`\`\`

4. Start the development server:
   \`\`\`bash
   npm start
   \`\`\`

5. Open http://localhost:3000 in your browser

## 📦 Build for Production

\`\`\`bash
npm run build
\`\`\`

This creates an optimized production build in the \`build\` folder.

## 🎨 Customization

- Edit \`App.js\` and components in \`/components\` folder
- Modify styles in \`styles.css\`
- Update dependencies in \`package.json\`

## 📝 Notes

- Uses Tailwind CSS via CDN
- Includes Lucide React icons
- Fully responsive and accessible
- Ready to deploy to Vercel, Netlify, or any static host

Generated by AI Landing Page Builder
`;

            zip.file("README.md", readme);

            // Generate and download the zip file
            const blob = await zip.generateAsync({ type: "blob" });
            saveAs(blob, `landing-page-${Date.now()}.zip`);

            console.log("Project exported successfully!");
        } catch (error) {
            console.error("Error creating zip:", error);
            alert("Failed to export project. Please try again.");
        }
    };

    const GetSandpackClient = async () => {
        if (action) {
            console.log("Action:", action);

            if (action?.actionType === "deploy") {
                try {
                    const client = previewRef.current?.getClient?.();
                    if (client && typeof (client as any).getCodeSandboxURL === 'function') {
                        const result = await (client as any).getCodeSandboxURL();
                        console.log(result);
                        window.open(`https://${result?.sandboxId}.csb.app/`, "_blank");
                    } else {
                        window.open("https://codesandbox.io/s/", "_blank");
                        alert("Deploy feature is limited in this Sandpack version. Opening CodeSandbox manually.");
                    }
                } catch (error) {
                    console.error("Error deploying to CodeSandbox:", error);
                    alert("Failed to deploy. Opening CodeSandbox manually.");
                    window.open("https://codesandbox.io/s/", "_blank");
                }
            } else if (action?.actionType === "export") {
                await downloadAsZip();
            }

            setAction(null);
        }
    };

    return (
        <div style={{ height: "100%", width: "100%", display: "flex", flex: 1, flexDirection: "column" }}>
            <SandpackPreview
                style={{ height: "100%", width: "100%", flex: 1, minHeight: 0 }}
                ref={previewRef}
                showNavigator={true}
                showOpenInCodeSandbox={false}
                showRefreshButton={true}
                actionsChildren={undefined}
            />
        </div>
    );
}

export default SandpackPreviewClient;
